services:
  user-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-server
    # ports:
    #   - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      DB_URL: ${DB_URL}
      KEYCLOAK_AUTH_SERVER_URL: ${KEYCLOAK_AUTH_SERVER_URL}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_SERVER_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      SERVER_PORT: ${SERVER_PORT}
    networks:
      - gupang-network

networks:
  gupang-network:
    external: true
